FROM node:20.15.1-alpine3.20 as build-stage
ARG VITE_BASE_URL
ENV VITE_BASE_URL=${VITE_BASE_URL}
WORKDIR /app/
COPY package*.json .
RUN npm install
COPY . .
RUN ["npm", "run", "build"]

FROM nginx:1.25.1-alpine3.17-slim
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]